# DAQ Channel Configuration - Optimized for Performance
# This configuration reduces CPU and memory usage for slower computers
# while maintaining full functionality

# Analog Input Channels (16 channels)
analog_channels:
  - name: "HUMAC 1 Direction"
    short_name: "HUMAC-DIR"
    unit: "V"
    range: [-10, 10]
  
  - name: "HUMAC 2 Velocity"
    short_name: "HUMAC-VEL"
    unit: "V"
    range: [-10, 10]
  
  - name: "HUMAC 3 Torque"
    short_name: "HUMAC-TRQ"
    unit: "V"
    range: [-10, 10]
  
  - name: "HUMAC 4 Position"
    short_name: "HUMAC-POS"
    unit: "V"
    range: [-10, 10]
  
  - name: "KINARM Task Start"
    short_name: "KIN-TASK"
    unit: "V"
    range: [0, 5]
  
  - name: "KINARM Recording Start"
    short_name: "KIN-REC"
    unit: "V"
    range: [0, 5]
  
  - name: "KINARM Repetition Start"
    short_name: "KIN-REP"
    unit: "V"
    range: [0, 5]
  
  - name: "VICON Recording start/stop"
    short_name: "VICON-REC"
    unit: "V"
    range: [0, 5]
  
  - name: "VICON frame capture"
    short_name: "VICON-FRAME"
    unit: "V"
    range: [0, 5]
  
  - name: "Grip Trigger"
    short_name: "GRIP-TRIG"
    unit: "V"
    range: [0, 5]
  
  - name: "Grip Dynomometer"
    short_name: "GRIP-DYN"
    unit: "V"
    range: [-10, 10]
  
  - name: "Pinch Dynomometer"
    short_name: "PINCH-DYN"
    unit: "V"
    range: [-10, 10]
  
  - name: "Arduino Trigger"
    short_name: "ARD-TRIG"
    unit: "V"
    range: [0, 5]
  
  - name: "Arduino Amplitude"
    short_name: "ARD-AMP"
    unit: "V"
    range: [-10, 10]
  
  - name: "Arduino Stim Active"
    short_name: "ARD-STIM"
    unit: "V"
    range: [0, 5]
  
  - name: "TMS Trig OUT"
    short_name: "TMS-OUT"
    unit: "V"
    range: [0, 5]

# EMG Channels (4 channels)
emg_channels:
  - name: "Left Abductor Pollicis Brevis"
    short_name: "L-APB"
    muscle_group: "Hand"
    unit: "mV"
    range: [-5, 5]
    hardware_channel: 17
  
  - name: "Left Flexor"
    short_name: "L-FLEX"
    muscle_group: "Forearm"
    unit: "mV"
    range: [-5, 5]
    hardware_channel: 27
  
  - name: "Left First Dorsal Interosseous"
    short_name: "L-FDI"
    muscle_group: "Hand"
    unit: "mV"
    range: [-5, 5]
    hardware_channel: 29
  
  - name: "Not Connected"
    short_name: "NC"
    muscle_group: "None"
    unit: "mV"
    range: [-5, 5]
    hardware_channel: 23

# Hardware Configuration - Optimized for slower computers
hardware:
  device_name: "Dev1"
  sampling_rate: 1000        # Lower sampling rate for better performance
  update_rate: 0.2           # Update every 0.2 seconds
  history_duration: 2.0      # Show 2 seconds of data history
  
  # Terminal configurations
  analog_terminal_config: "single_ended_non_referenced"
  emg_terminal_config: "single_ended"

# File Settings
file_settings:
  default_directory: "data"
  default_project: "swallow_JET"
  file_format: "binary"
  metadata_format: "json"
  
# Display Settings - Optimized for performance
display:
  emg_y_range: [-1, 1]
  analog_y_range: [-1, 6]
  plot_colors:
    emg: "#8B0000"
    analog: "#2E8B57"
  grid_columns: 2            # Show 2 columns of plots
  
# Performance Settings for Slow PCs
performance:
  web_update_interval: 200   # Web interface updates every 200ms
  status_update_interval: 5000  # Status updates every 5 seconds
  buffer_multiplier: 5       # Smaller hardware buffer for better performance
  plot_line_width: 1         # Thin lines for faster rendering
  enable_antialiasing: false # Disable antialiasing for speed